title:             Lin Cong
tagline:           Ph.D. | Artificial Intelligence & Robotics
show_downloads:    false
baseurl:           ""
locale:            "en"
# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
